name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test hospital_middleware_system
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug service folder
        run: |
          echo "Root folder: $PWD"
          ls -la
          ls -la service

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Go mod download
        run: |
          cd service
          go mod tidy
          go mod download

      - name: Run tests
        run: |
          cd service
          go test ./internal/... ./pkg/... ./tests/... -v -race

      - name: Build binary
        run: |
          cd service
          go build -v -o service ./cmd

  docker:
    name: Docker Build & Push
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login CLI
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          cd service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hospital_middleware_system:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/hospital_middleware_system:latest \
                     ${{ secrets.DOCKER_USERNAME }}/hospital_middleware_system:${{ github.sha }}

      - name: Push Docker image
        run: |
          cd service
          docker push ${{ secrets.DOCKER_USERNAME }}/hospital_middleware_system:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/hospital_middleware_system:${{ github.sha }}
